### ISSUE TITLE
May I become a maintainer for `defun-core`/`defun` on Stackage?

### ISSUE THREAD

**Issue by raehik** [phadej/defun#4]
Hi, thanks a ton for defun-- it was the first defunctionalization explanation that made sense to me. I'm using it in a handful of libraries, currently [symbol-parser](https://hackage.haskell.org/package/symbol-parser), [type-level-bytestrings](https://hackage.haskell.org/package/type-level-bytestrings), [type-level-show](https://github.com/raehik/type-level-show). I want to get these on Stackage, largely for the selfish reason of being able to search them with Hoogle (and because they're foundational for some other libraries of mine).

For that, I need defun(-core) on Stackage. I would gladly sign up as the maintainer if you would give me permission. I also don't mind waiting if you'd like to do it yourself. (On a quick check defun-core builds fine with the current Stackage nightly, unsurprisingly.)

**Comment by phadej** [comment]
I don't care about Stackage. If you wish to have `defun` there, you're welcome to add it there.

**Comment by raehik** [comment]
Appreciated :)
